fixed all rebocop erros and improved readme file
AnthonyTC89/rspec_enumerable_methods pull request #1
Opened 2019-08-25 06:53 UTC by RoyNyaga

2019-08-25 10:15 UTC, bolah2009 requested changes
# Awesome Job Team :clap: 

Check out the review comments and issue (#2). :blush: 

Fix this and submit another code review request. :ok_hand: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-25 10:15 UTC, bolah2009 commented on lib/iterator_methods.rb
>    array.my_inject { |elem, n| elem + n }
#### `REQUIRED`

This method seems not to be tested. Other cases that are not tested is referenced in this issue(#2).

2019-08-25 10:15 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +      arr.my_each { |_i| count += 1 }
#### `REQUIRED`

Consider deleting unused argument.

```suggestion
      arr.my_each { count += 1 }
```

2019-08-25 10:15 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +      arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
#### `REQUIRED`

Consider using `let` instead, this file have different places `arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]` was defined.
Learn more [here](https://github.com/rubocop-hq/rspec-style-guide#let-blocks)

2019-08-25 10:15 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +  describe ' #my_all?' do
#### `REQUIRED`

Add test for cases where `block` is not given. See issue #2.

2019-08-25 10:15 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +  describe ' #my_any?' do
#### `REQUIRED`

Add test for cases where `block` is not given. See issue #2.

2019-08-25 10:15 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +      expect(arr.length).to eql(arr.my_count)
#### `REQUIRED`

Add the method to be tested in the `expect` parameter.

```ruby
   expect(actual).to be(expected) # passes if actual.equal?(expected)
```

Learn more [here](https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers)

```suggestion
      expect(arr.my_count).to eql(arr.length)
```

2019-08-25 10:15 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +      expect(arr.count).to eql(arr.my_count)
#### `REQUIRED`

Add the method to be tested in the `expect` parameter.

```ruby
   expect(actual).to be(expected) # passes if actual.equal?(expected)
```

Learn more [here](https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers)

```suggestion
      expect(arr.my_count).to eql(arr.count)
```

2019-08-26 02:56 UTC, RoyNyaga commented
Thanks for the review sir will fix those today


On Sun, Aug 25, 2019 at 11:15 AM BOLA AHMED BUARI <notifications@github.com>
wrote:

> *@bolah2009* requested changes on this pull request.
> Awesome Job Team 👏
>
> Check out the review comments and issue (#2
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/issues/2>) and
> submit another code review.
>
> Good luck with your next submission. 🌟
>
> Cheers
> Bola <https://bolabuari.com/>
> ------------------------------
>
> In lib/iterator_methods.rb
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/pull/1#discussion_r317390334>
> :
>
> > @@ -85,7 +85,7 @@ def multiply_els(array)
>
>    array.my_inject { |elem, n| elem + n }
>
>
> REQUIRED
>
> This method seems not to be tested. Other cases that are not tested is
> referenced in this issue(#2
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/issues/2>).
> ------------------------------
>
> In spec/enumerable_spec.rb
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/pull/1#discussion_r317390557>
> :
>
> > \ No newline at end of file
>
> +  describe '#my_each' do
>
> +    it 'iterates through numbers in an array' do
>
> +      arr = [1, 2, 3, 4, 5]
>
> +      count = 0
>
> +      arr.my_each { |_i| count += 1 }
>
>
> REQUIRED
>
> Consider deleting unused argument.
> ⬇️ Suggested change
>
> -      arr.my_each { |_i| count += 1 }
>
> +      arr.my_each { count += 1 }
>
>
> ------------------------------
>
> In spec/enumerable_spec.rb
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/pull/1#discussion_r317390678>
> :
>
> > +    it ' iterates and compare if any element in the array have the condition in the block' do
>
> +      arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>
> +      cond = arr.my_any? { |elem| elem == 4 }
>
> +      expect(cond).to be true
>
> +    end
>
> +
>
> +    it ' iterates and compare if any element in the array have the condition in the block' do
>
> +      arr = %w[word school bus eat]
>
> +      cond = arr.my_any? { |elem| elem == 'take' }
>
> +      expect(cond).to be false
>
> +    end
>
> +  end
>
> +
>
> +  describe '#my_none?' do
>
> +    it 'returns true' do
>
> +      arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
>
>
> REQUIRED
>
> Consider using let instead, this file have different places arr = [1, 2,
> 3, 4, 5, 6, 7, 8, 9] was defined.
> Learn more here
> <https://github.com/rubocop-hq/rspec-style-guide#let-blocks>
> ------------------------------
>
> In spec/enumerable_spec.rb
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/pull/1#discussion_r317390787>
> :
>
> > +
>
> +  describe ' #my_select' do
>
> +    it ' iterates and select odd numbers in an array' do
>
> +      arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>
> +      arr_select = arr.my_select(&:odd?)
>
> +      expect(arr_select).to match_array([1, 3, 5, 7, 9])
>
> +    end
>
> +
>
> +    it 'iterates and returns string of lenght 5' do
>
> +      arr2 = %w[how there many carry taken yes]
>
> +      arr_select2 = arr2.my_select { |word| word.length == 5 }
>
> +      expect(arr_select2).to match_array(%w[there carry taken])
>
> +    end
>
> +  end
>
> +
>
> +  describe ' #my_all?' do
>
>
> REQUIRED
>
> Add test for cases where block is not given. See issue(#2
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/issues/2>).
> ------------------------------
>
> In spec/enumerable_spec.rb
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/pull/1#discussion_r317390812>
> :
>
> > +
>
> +  describe ' #my_all?' do
>
> +    it 'returns elements less than 10' do
>
> +      arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>
> +      cond = arr.my_all? { |elem| elem < 10 }
>
> +      expect(cond).to be true
>
> +    end
>
> +
>
> +    it ' returns true when all elements start with s' do
>
> +      arr = %w[school soccer sugar rain]
>
> +      cond = arr.my_all? { |elem| elem[0] == 's' }
>
> +      expect(cond).to be false
>
> +    end
>
> +  end
>
> +
>
> +  describe ' #my_any?' do
>
>
> REQUIRED
>
> Add test for cases where block is not given. See issue(#2
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/issues/2>).
> ------------------------------
>
> In spec/enumerable_spec.rb
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/pull/1#discussion_r317391026>
> :
>
> > +    it 'returns true' do
>
> +      arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
>
> +      cond = arr.my_none? { |elem| elem == 10 }
>
> +      expect(cond).to be true
>
> +    end
>
> +    it 'returns false' do
>
> +      arr = %w[name lastname age]
>
> +      cond = arr.my_none? { |elem| elem == 'name' }
>
> +      expect(cond).to be false
>
> +    end
>
> +  end
>
> +
>
> +  describe ' #my_count' do
>
> +    it ' without arguments nor block' do
>
> +      arr = [1, 2, 3, 4]
>
> +      expect(arr.length).to eql(arr.my_count)
>
>
> REQUIRED
>
> Add the method to be tested in the expect parameter.
>
>    expect(actual).to be(expected) # passes if actual.equal?(expected)
>
> Learn more here
> <https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers>
> ⬇️ Suggested change
>
> -      expect(arr.length).to eql(arr.my_count)
>
> +      expect(arr.my_count).to eql(arr.length)
>
>
> ------------------------------
>
> In spec/enumerable_spec.rb
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/pull/1#discussion_r317391103>
> :
>
> > +      expect(arr.my_count(3)).to eql(2)
>
> +    end
>
> +
>
> +    it ' with a block' do
>
> +      count = [1, 3, 3, 4].my_count { |num| num > 1 }
>
> +      expect(count).to eql(3)
>
> +    end
>
> +
>
> +    it ' with a block and argument' do
>
> +      count = [1, 3, 3, 4].my_count(3) { |num| num > 1 }
>
> +      expect(count).to eql(2)
>
> +    end
>
> +
>
> +    it 'comparing count and my_count methods' do
>
> +      arr = [1, 2, 3, 4]
>
> +      expect(arr.count).to eql(arr.my_count)
>
>
> REQUIRED
>
> Add the method to be tested in the expect parameter.
>
>    expect(actual).to be(expected) # passes if actual.equal?(expected)
>
> Learn more here
> <https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers>
> ⬇️ Suggested change
>
> -      expect(arr.count).to eql(arr.my_count)
>
> +      expect(arr.my_count).to eql(arr.count)
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AnthonyTC89/rspec_enumerable_methods/pull/1?email_source=notifications&email_token=ALZGFHNBGU5ENH3KEFFSKJ3QGJLU7A5CNFSM4IPIGECKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCCTDI4Y#pullrequestreview-279327859>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALZGFHNGVZFGCTHEV4PFAO3QGJLU7ANCNFSM4IPIGECA>
> .
>

2019-08-26 16:34 UTC, AnthonyTC89 commented on lib/iterator_methods.rb
>    array.my_inject { |elem, n| elem + n }
done!

2019-08-26 17:35 UTC, AnthonyTC89 commented on spec/enumerable_spec.rb
> +  describe ' #my_all?' do
done!

2019-08-26 17:35 UTC, AnthonyTC89 commented on spec/enumerable_spec.rb
> +  describe ' #my_any?' do
done!

2019-08-26 17:36 UTC, AnthonyTC89 commented on spec/enumerable_spec.rb
> +      expect(arr.length).to eql(arr.my_count)
nice view!.. done!

2019-08-26 17:36 UTC, AnthonyTC89 commented on spec/enumerable_spec.rb
> +      expect(arr.count).to eql(arr.my_count)
done!

2019-08-26 23:18 UTC, Ispirett approved these changes
Greate job!!!! @RoyNyaga @AnthonyTC89  :1st_place_medal:   
This project looks good to me you can merge.

##### Before merge 
please delete commentied code in you ` iterator_methods1

#### Optional not required to complete this project.
consider using this flag in you `.rspec` file `--format documentation`

2019-08-27 09:51 UTC, merged